/*
 * Copyright 2026
 * Licensed under the Apache License, Version 2.0 (the "License");
 */

// Zicond
`DEFINE_SCALAR_EXT_INSTR(CZERO_EQZ, R_FORMAT, ARITHMETIC, RV32ZICOND)
`DEFINE_SCALAR_EXT_INSTR(CZERO_NEZ, R_FORMAT, ARITHMETIC, RV32ZICOND)

// Zimop/Zcmop.  The immediate field is used as the MOP code-point selector.
`DEFINE_SCALAR_EXT_INSTR(MOP_R,  R_FORMAT,  ARITHMETIC, RV32ZIMOP, UIMM)
`DEFINE_SCALAR_EXT_INSTR(MOP_RR, R_FORMAT,  ARITHMETIC, RV32ZIMOP, UIMM)
`DEFINE_SCALAR_EXT_INSTR(C_MOP,  CI_FORMAT, ARITHMETIC, RV32ZCMOP, UIMM)

// Cache-block management, zero, and prefetch operations.
`DEFINE_SCALAR_EXT_INSTR(CBO_CLEAN,  I_FORMAT, SYNCH, RV32ZICBOM)
`DEFINE_SCALAR_EXT_INSTR(CBO_FLUSH,  I_FORMAT, SYNCH, RV32ZICBOM)
`DEFINE_SCALAR_EXT_INSTR(CBO_INVAL,  I_FORMAT, SYNCH, RV32ZICBOM)
`DEFINE_SCALAR_EXT_INSTR(CBO_ZERO,   I_FORMAT, SYNCH, RV32ZICBOZ)
`DEFINE_SCALAR_EXT_INSTR(PREFETCH_I, I_FORMAT, SYNCH, RV32ZICBOP)
`DEFINE_SCALAR_EXT_INSTR(PREFETCH_R, I_FORMAT, SYNCH, RV32ZICBOP)
`DEFINE_SCALAR_EXT_INSTR(PREFETCH_W, I_FORMAT, SYNCH, RV32ZICBOP)

// Zbkb/Zbkx instructions which are not already supplied by Zbb.
`DEFINE_SCALAR_EXT_INSTR(BREV8,  I_FORMAT, SHIFT,   RV32ZBKB)
`DEFINE_SCALAR_EXT_INSTR(ZIP,    I_FORMAT, LOGICAL, RV32ZBKB)
`DEFINE_SCALAR_EXT_INSTR(UNZIP,  I_FORMAT, LOGICAL, RV32ZBKB)
`DEFINE_SCALAR_EXT_INSTR(XPERM4, R_FORMAT, LOGICAL, RV32ZBKX)
`DEFINE_SCALAR_EXT_INSTR(XPERM8, R_FORMAT, LOGICAL, RV32ZBKX)

// AES encryption/decryption and key-schedule instructions.
`DEFINE_SCALAR_EXT_INSTR(AES32DSI,  R_FORMAT, LOGICAL, RV32ZKND, UIMM)
`DEFINE_SCALAR_EXT_INSTR(AES32DSMI, R_FORMAT, LOGICAL, RV32ZKND, UIMM)
`DEFINE_SCALAR_EXT_INSTR(AES32ESI,  R_FORMAT, LOGICAL, RV32ZKNE, UIMM)
`DEFINE_SCALAR_EXT_INSTR(AES32ESMI, R_FORMAT, LOGICAL, RV32ZKNE, UIMM)
`DEFINE_SCALAR_EXT_INSTR(AES64DS,   R_FORMAT, LOGICAL, RV64ZKND)
`DEFINE_SCALAR_EXT_INSTR(AES64DSM,  R_FORMAT, LOGICAL, RV64ZKND)
`DEFINE_SCALAR_EXT_INSTR(AES64ES,   R_FORMAT, LOGICAL, RV64ZKNE)
`DEFINE_SCALAR_EXT_INSTR(AES64ESM,  R_FORMAT, LOGICAL, RV64ZKNE)
`DEFINE_SCALAR_EXT_INSTR(AES64IM,   I_FORMAT, LOGICAL, RV64ZKND)
`DEFINE_SCALAR_EXT_INSTR(AES64KS1I, I_FORMAT, LOGICAL, RV64ZKND, UIMM)
`DEFINE_SCALAR_EXT_INSTR(AES64KS2,  R_FORMAT, LOGICAL, RV64ZKND)

// SHA-2 instructions.  SHA-256 is common to RV32/RV64; SHA-512 has the
// native RV64 unary forms and the paired RV32 forms.
`DEFINE_SCALAR_EXT_INSTR(SHA256SIG0, I_FORMAT, LOGICAL, RV32ZKNH)
`DEFINE_SCALAR_EXT_INSTR(SHA256SIG1, I_FORMAT, LOGICAL, RV32ZKNH)
`DEFINE_SCALAR_EXT_INSTR(SHA256SUM0, I_FORMAT, LOGICAL, RV32ZKNH)
`DEFINE_SCALAR_EXT_INSTR(SHA256SUM1, I_FORMAT, LOGICAL, RV32ZKNH)
`DEFINE_SCALAR_EXT_INSTR(SHA512SIG0, I_FORMAT, LOGICAL, RV64ZKNH)
`DEFINE_SCALAR_EXT_INSTR(SHA512SIG1, I_FORMAT, LOGICAL, RV64ZKNH)
`DEFINE_SCALAR_EXT_INSTR(SHA512SUM0, I_FORMAT, LOGICAL, RV64ZKNH)
`DEFINE_SCALAR_EXT_INSTR(SHA512SUM1, I_FORMAT, LOGICAL, RV64ZKNH)
`DEFINE_SCALAR_EXT_INSTR(SHA512SIG0H, R_FORMAT, LOGICAL, RV32ZKNH)
`DEFINE_SCALAR_EXT_INSTR(SHA512SIG0L, R_FORMAT, LOGICAL, RV32ZKNH)
`DEFINE_SCALAR_EXT_INSTR(SHA512SIG1H, R_FORMAT, LOGICAL, RV32ZKNH)
`DEFINE_SCALAR_EXT_INSTR(SHA512SIG1L, R_FORMAT, LOGICAL, RV32ZKNH)
`DEFINE_SCALAR_EXT_INSTR(SHA512SUM0R, R_FORMAT, LOGICAL, RV32ZKNH)
`DEFINE_SCALAR_EXT_INSTR(SHA512SUM1R, R_FORMAT, LOGICAL, RV32ZKNH)

// ShangMi algorithms.
`DEFINE_SCALAR_EXT_INSTR(SM4ED, R_FORMAT, LOGICAL, RV32ZKSED, UIMM)
`DEFINE_SCALAR_EXT_INSTR(SM4KS, R_FORMAT, LOGICAL, RV32ZKSED, UIMM)
`DEFINE_SCALAR_EXT_INSTR(SM3P0, I_FORMAT, LOGICAL, RV32ZKSH)
`DEFINE_SCALAR_EXT_INSTR(SM3P1, I_FORMAT, LOGICAL, RV32ZKSH)
